/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lab4.src.view;

import br.com.lab4.src.jdbc.DataBase;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import br.com.lab4.utils.JNumberFormatField;
import br.com.lab4.src.model.CadastroModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import br.com.lab4.utils.DefineQtdeCaracter;

/**
 *
 * @author Raul
 */
public class CadastroView extends javax.swing.JFrame {

    CadastroModel cadastro = new CadastroModel();

    /**
     * Creates new form CadastroView
     */
    public CadastroView() {
        initComponents();
        confTelaCadastro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloCadastro = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigoCad = new javax.swing.JTextField();
        lblNomeCad = new javax.swing.JLabel();
        txtNomeCad = new javax.swing.JTextField();
        txtNomeCad.setDocument(new DefineQtdeCaracter(60));
        lblFuncCad = new javax.swing.JLabel();
        txtFuncCad = new javax.swing.JTextField();
        txtFuncCad.setDocument(new DefineQtdeCaracter(30));
        lblDataCad = new javax.swing.JLabel();
        txtDatCad = new org.jdesktop.swingx.JXDatePicker();
        lblSalCad = new javax.swing.JLabel();
        txtSalCad = new JNumberFormatField(new DecimalFormat("R$ 0.00")) { 
            {// limita a 4 
                // caracteres 
                setLimit(7); 
            } }
            ;
            btnCadastrar = new javax.swing.JButton();
            btnNovo = new javax.swing.JButton();
            btnLimpar = new javax.swing.JButton();
            btnVoltar = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            lblTituloCadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            lblTituloCadastro.setText("Cadastro de Funcionário");

            lblCodigo.setText("Código:");

            txtCodigoCad.setEditable(false);
            txtCodigoCad.setEnabled(false);

            lblNomeCad.setText("Nome Completo:");

            lblFuncCad.setText("Função:");

            lblDataCad.setText("Data Contratação:");

            txtDatCad.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtDatCadActionPerformed(evt);
                }
            });

            lblSalCad.setText("Salário:");

            txtSalCad.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtSalCadActionPerformed(evt);
                }
            });

            btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lab4/img/Save.png"))); // NOI18N
            btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCadastrarActionPerformed(evt);
                }
            });

            btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lab4/img/New.png"))); // NOI18N
            btnNovo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnNovoActionPerformed(evt);
                }
            });

            btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lab4/img/Eraser.png"))); // NOI18N
            btnLimpar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnLimparActionPerformed(evt);
                }
            });

            btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lab4/img/back.png"))); // NOI18N
            btnVoltar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnVoltarActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTituloCadastro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                            .addComponent(lblCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCodigoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNomeCad)
                            .addGap(10, 10, 10)
                            .addComponent(txtNomeCad))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDataCad)
                            .addGap(18, 18, 18)
                            .addComponent(txtDatCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblFuncCad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFuncCad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSalCad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtSalCad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodigoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCodigo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNomeCad)
                                .addComponent(txtNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFuncCad)
                                .addComponent(txtFuncCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSalCad)
                                .addComponent(txtSalCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblTituloCadastro))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDataCad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDatCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(btnLimpar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        try {
            IndexView ci = new IndexView();
            ci.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("tela consulta 187 \n" + e);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtSalCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalCadActionPerformed

    }//GEN-LAST:event_txtSalCadActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        if (txtNomeCad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha o nome do funcionário!");
        } else {
            if (txtFuncCad.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor, preencha a função do funcionário!");
            } else {
                if (txtSalCad.getText().equals("R$ 0.00")) {
                    JOptionPane.showMessageDialog(null, "Por favor, preencha o salário do funcionário!");

                } else {
                    cadastrarFuncionario();
                }

            }

        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtDatCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatCadActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        String mensagem = "Há campos preenchidos. Deseja realmente cadastrar um novo funcionário?";
        if (!txtCodigoCad.getText().equals("") || !txtFuncCad.getText().equals("")
                || !txtNomeCad.getText().equals("") || !txtSalCad.getText().equals("R$ 0.00")) {
            limparCamposCadastro(mensagem);
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        String mensagem = "Deseja realmente limpar os campos?";
        limparCamposCadastro(mensagem);
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataCad;
    private javax.swing.JLabel lblFuncCad;
    private javax.swing.JLabel lblNomeCad;
    private javax.swing.JLabel lblSalCad;
    private javax.swing.JLabel lblTituloCadastro;
    private javax.swing.JTextField txtCodigoCad;
    private org.jdesktop.swingx.JXDatePicker txtDatCad;
    private javax.swing.JTextField txtFuncCad;
    private javax.swing.JTextField txtNomeCad;
    private javax.swing.JTextField txtSalCad;
    // End of variables declaration//GEN-END:variables
    private void confTelaCadastro() {
        //Nome na barra superior da janela
        this.setTitle("Cadastro de Funcionário");
        //Impossível Redimensionar 
        this.setResizable(false);
        //Fechar toda a Aplicação ao clicar no botão Fechar
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //Centraliza Tela
        this.setLocationRelativeTo(null);
        txtNomeCad.requestFocus();

    }

    //Data pra String
    public String dateToString(Date d) {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String dataConvertida = df.format(d);

        return dataConvertida;
    }

    public double formataSalario(String salario) {
        salario = salario.replace("R$ ", "");
        double salarioConvertido = Double.parseDouble(salario);

        return salarioConvertido;
    }

    public void limparCamposCadastro(String mensagemJOP) {
        boolean sim = mensagemConfirmacao(mensagemJOP);
        if (sim == true) {
            txtCodigoCad.setText(null);
            txtNomeCad.setText(null);
            txtFuncCad.setText(null);
            txtSalCad.setText(null);
            txtDatCad.setDate(getDataAtual());
        }

    }

    public Date getDataAtual() {
        Date today = Calendar.getInstance().getTime();
        return today;
    }

    private void cadastrarFuncionario() {
        String sql = "insert into colaborador (nomecompleto,funcao,datacadastro,salario) values "
                + "(?,?,?,?)";

        String nomeCompleto = txtNomeCad.getText();
        String funcao = txtFuncCad.getText();
        String dataCadastro = dateToString(txtDatCad.getDate());
        double salario = formataSalario(txtSalCad.getText());

        Connection con;
        PreparedStatement st;
        try {
            con = DataBase.getConnection();
            st = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            st.setString(1, nomeCompleto);
            st.setString(2, funcao);
            st.setString(3, dataCadastro);
            st.setDouble(4, salario);

            boolean resultado = st.execute();
            ResultSet rt = st.getGeneratedKeys();

            while (rt.next()) {
                long id = rt.getLong("CODIGOFUNCIONARIO");
                txtCodigoCad.setText(String.valueOf(id));
                System.out.println(resultado + " ID: " + id);
            }
            JOptionPane.showMessageDialog(null, "Funcionário Cadastrado com sucesso.");

            rt.close();
            st.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean mensagemConfirmacao(String mensagem) {
        boolean certeza = false;
        int resposta = JOptionPane.showConfirmDialog(null, mensagem, "Confirmação", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            return certeza;
        }

        return certeza;

    }
}
