/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lab4.src.view;

import br.com.lab4.utils.CellRenderer;
import br.com.lab4.src.jdbc.DataBase;
import br.com.lab4.utils.JNumberFormatField;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import br.com.lab4.utils.CellRenderer;
import java.awt.event.KeyEvent;

/**
 *
 * @author Raul
 */
public class ConsultaView extends javax.swing.JFrame {

    CadastroView view = new CadastroView();

    /**
     * Creates new form ConsultaModel
     */
    public ConsultaView() {
        initComponents();
        confTelaConsulta();
        confTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGNomeCodigo = new javax.swing.ButtonGroup();
        scpTabela = new javax.swing.JScrollPane();
        tabPesquisa = new javax.swing.JTable();
        tabPesquisa.setDefaultRenderer(Object.class, new CellRenderer());
        lblTituloTela = new javax.swing.JLabel();
        lblFuncaoConsulta = new javax.swing.JLabel();
        lblSalarioConsulta = new javax.swing.JLabel();
        rbtnFuncaoConsulta = new javax.swing.JRadioButton();
        rbtnSalario = new javax.swing.JRadioButton();
        btnPesquisar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtFuncaoConsulta = new javax.swing.JTextField();
        cbnOperadorLogico = new javax.swing.JComboBox();
        txtSalIniConsulta = new JNumberFormatField(new DecimalFormat("R$ 0.00")) { 
            {// limita a 4 
                // caracteres 
                setLimit(7); 
            } }
            ;
            txtSalFimConsulta = new JNumberFormatField(new DecimalFormat("R$ 0.00")) { 
                {// limita a 4 
                    // caracteres 
                    setLimit(7); 
                } }
                ;
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                tabPesquisa.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                    },
                    new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                    }
                ));
                scpTabela.setViewportView(tabPesquisa);

                lblTituloTela.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                lblTituloTela.setText("Consulta de Funcionários");

                lblFuncaoConsulta.setText("Função:");

                lblSalarioConsulta.setText("Salário:");

                btnGNomeCodigo.add(rbtnFuncaoConsulta);
                rbtnFuncaoConsulta.setMargin(new java.awt.Insets(4, 4, 4, 4));
                rbtnFuncaoConsulta.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        rbtnFuncaoConsultaActionPerformed(evt);
                    }
                });

                btnGNomeCodigo.add(rbtnSalario);
                rbtnSalario.setAlignmentX(2.0F);
                rbtnSalario.setAlignmentY(1.0F);
                rbtnSalario.setMargin(new java.awt.Insets(4, 4, 4, 2));
                rbtnSalario.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        rbtnSalarioActionPerformed(evt);
                    }
                });

                btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lab4/img/search.png.png"))); // NOI18N
                btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnPesquisarActionPerformed(evt);
                    }
                });
                btnPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        btnPesquisarKeyPressed(evt);
                    }
                });

                btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lab4/img/back.png"))); // NOI18N
                btnVoltar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnVoltarActionPerformed(evt);
                    }
                });

                txtFuncaoConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        txtFuncaoConsultaKeyPressed(evt);
                    }
                });

                cbnOperadorLogico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menor que...", "Menor ou igual que...", "Igual à...", "Maior que...", "Maior ou igual que..", "Diferente de...", "Entre..." }));
                cbnOperadorLogico.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        cbnOperadorLogicoActionPerformed(evt);
                    }
                });

                txtSalIniConsulta.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtSalIniConsultaActionPerformed(evt);
                    }
                });

                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lab4/img/garbage.png"))); // NOI18N
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scpTabela)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTituloTela)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtnFuncaoConsulta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFuncaoConsulta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFuncaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtnSalario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSalarioConsulta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSalIniConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addComponent(cbnOperadorLogico, 0, 145, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSalFimConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTituloTela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFuncaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFuncaoConsulta))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSalarioConsulta)
                                        .addComponent(txtSalIniConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbnOperadorLogico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSalFimConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rbtnSalario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnFuncaoConsulta)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scpTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar)
                            .addComponent(jButton1)
                            .addComponent(btnPesquisar))
                        .addContainerGap())
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void rbtnSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSalarioActionPerformed
        if (rbtnSalario.isSelected() == true) {
            desativaFuncao();
            txtSalIniConsulta.requestFocus();

            if (cbnOperadorLogico.isEnabled() == false
                    || txtSalIniConsulta.isEnabled() == false || txtSalIniConsulta.isEditable() == false
                    || txtSalFimConsulta.isEnabled() == false || txtSalFimConsulta.isEditable() == false) {
                ativaSalario();

            }
        }
    }//GEN-LAST:event_rbtnSalarioActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        try {
            IndexView ci = new IndexView();
            ci.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("tela consulta 187 \n" + e);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void rbtnFuncaoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFuncaoConsultaActionPerformed
        if (rbtnFuncaoConsulta.isSelected() == true) {
            desativaSalario();
            txtFuncaoConsulta.requestFocus();

            if (txtFuncaoConsulta.isEnabled() == false || txtFuncaoConsulta.isEditable() == false) {
                ativaFuncao();
            }
        }
    }//GEN-LAST:event_rbtnFuncaoConsultaActionPerformed

    private void txtSalIniConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalIniConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalIniConsultaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        pesquisarFuncionario();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPesquisarKeyPressed

    }//GEN-LAST:event_btnPesquisarKeyPressed

    private void txtFuncaoConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFuncaoConsultaKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            pesquisarFuncionario();
        }
    }//GEN-LAST:event_txtFuncaoConsultaKeyPressed

    private void cbnOperadorLogicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnOperadorLogicoActionPerformed
        int opcao = cbnOperadorLogico.getSelectedIndex();

        if (opcao == 6) {
            txtSalFimConsulta.setEnabled(true);
            txtSalFimConsulta.setEditable(true);
        } else {
            txtSalFimConsulta.setEnabled(false);
            txtSalFimConsulta.setEditable(false);
            txtSalFimConsulta.setText("R$ 0,00");
        }
    }//GEN-LAST:event_cbnOperadorLogicoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGNomeCodigo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox cbnOperadorLogico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblFuncaoConsulta;
    private javax.swing.JLabel lblSalarioConsulta;
    private javax.swing.JLabel lblTituloTela;
    private javax.swing.JRadioButton rbtnFuncaoConsulta;
    private javax.swing.JRadioButton rbtnSalario;
    private javax.swing.JScrollPane scpTabela;
    private javax.swing.JTable tabPesquisa;
    private javax.swing.JTextField txtFuncaoConsulta;
    private javax.swing.JTextField txtSalFimConsulta;
    private javax.swing.JTextField txtSalIniConsulta;
    // End of variables declaration//GEN-END:variables
    private void confTelaConsulta() {
        //Nome na barra superior da janela
        this.setTitle("Consulta de Funcionário");
        //Impossível Redimensionar 
        this.setResizable(false);
        //Fechar toda a Aplicação ao clicar no botão Fechar
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //Centraliza Tela
        this.setLocationRelativeTo(null);
        rbtnFuncaoConsulta.setSelected(true);
        txtFuncaoConsulta.requestFocus();
        desativaSalario();
    }

    private void confTabela() {
        DefaultTableModel m = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        m.addColumn("Código");
        m.addColumn("Nome Funcionário");
        m.addColumn("Cargo");
        m.addColumn("Data de Contratação");
        m.addColumn("Salário");

        tabPesquisa.setModel(m);
        tabPesquisa.getColumnModel().getColumn(0).setMaxWidth(60);//Código do Funcionário
        tabPesquisa.getColumnModel().getColumn(1).setMaxWidth(400);//nome do funcionário
        tabPesquisa.getColumnModel().getColumn(2).setMaxWidth(400);//cargo
        tabPesquisa.getColumnModel().getColumn(3).setMaxWidth(200);//Data de Contratação
        tabPesquisa.getColumnModel().getColumn(4).setMaxWidth(100);//Salário

        //Centralizar nome da coluna
        ((DefaultTableCellRenderer) tabPesquisa.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
    }

    private void pesquisarFuncionario() {
        DefaultTableModel m = (DefaultTableModel) tabPesquisa.getModel();

        int linha = m.getRowCount();
        if (linha > 0) {
            for (int i = 0; i < linha; i++) {
                m.removeRow(0);
            }
        }

        Connection con;
        Statement st;

        String funcao = txtFuncaoConsulta.getText().toUpperCase();
        double salarioInicial = view.formataSalario(txtSalIniConsulta.getText());
        double salarioFinal = view.formataSalario(txtSalFimConsulta.getText());

        String sql = null;
        if (rbtnFuncaoConsulta.isSelected()) {
            sql = "select * from colaborador where funcao like '%" + funcao + "%'";
        } else if (rbtnSalario.isSelected()) {
            int operadorLogico = cbnOperadorLogico.getSelectedIndex();
            switch (operadorLogico) {
                case 0:
                    sql = "select * from colaborador where salario < " + salarioInicial;
                    break;
                case 1:
                    sql = "select * from colaborador where salario <= " + salarioInicial;
                    break;
                case 2:
                    sql = "select * from colaborador where salario = " + salarioInicial;
                    break;
                case 3:
                    sql = "select * from colaborador where salario > " + salarioInicial;
                    break;
                case 4:
                    sql = "select * from colaborador where salario >= " + salarioInicial;
                    break;
                case 5:
                    sql = "select * from colaborador where salario <> " + salarioInicial;
                    break;
                case 6:
                    sql = "select * from colaborador where salario between " + salarioInicial
                            + "and " + salarioFinal;
                    break;
            }

        }

        try {
            con = DataBase.getConnection();
            st = con.createStatement();
            st.execute(sql);

            ResultSet rt = st.getResultSet();

            while (rt.next()) {
                int codigo = rt.getInt("codigofuncionario");
                String nome = rt.getString("nomecompleto");
                String funcaoFunc = rt.getString("funcao");
                Date data = rt.getDate("datacadastro");
                double salario = rt.getDouble("salario");
                m.addRow(new Object[]{codigo, nome, funcaoFunc, data, salario});
            }
            tabPesquisa.setModel(m);

            rt.close();
            st.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void desativaSalario() {
        txtSalIniConsulta.setEditable(false);
        txtSalIniConsulta.setEnabled(false);
        txtSalFimConsulta.setEditable(false);
        txtSalFimConsulta.setEnabled(false);
        cbnOperadorLogico.setEnabled(false);
        txtSalFimConsulta.setText("");
        txtSalFimConsulta.setText("");
    }

    private void desativaFuncao() {
        txtFuncaoConsulta.setEditable(false);
        txtFuncaoConsulta.setEnabled(false);
        txtFuncaoConsulta.setText("");
    }

    private void ativaSalario() {
        txtSalIniConsulta.setEditable(true);
        txtSalIniConsulta.setEnabled(true);
        if (cbnOperadorLogico.getSelectedIndex() != 6) {
            txtSalFimConsulta.setEnabled(false);
            txtSalFimConsulta.setEditable(false);
            txtSalFimConsulta.setText("R$ 0,00");
        }
        cbnOperadorLogico.setEnabled(true);
    }

    private void ativaFuncao() {
        txtFuncaoConsulta.setEditable(true);
        txtFuncaoConsulta.setEnabled(true);
    }

}
